# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shapeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallconfiguration',
            name='timeChanged',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
