# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapeAPI', '0003_wallconfigurationcoord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallconfigurationcoord',
            old_name='timeChangedCoor',
            new_name='timeChanged',
        ),
    ]
