# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeAPI', '0004_auto_20171026_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallconfiguration',
            name='deviceID',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallconfigurationcoord',
            name='deviceID',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
