# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shapeAPI', '0005_auto_20171129_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
                ('timeChanged', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
